env: development
port: 7777
mysql:
  dbhost: localhost
  dbuser: root
  dbport: 3306
  dbpass:
  dbname: your_database
jwt:
  signing_key: your_secret_key
  exp: 24h
redis:
  host: localhost:6379
  pass:
  db: 0
